# Generated by Django 3.2.5 on 2021-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=15)),
                ('discount', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=45)),
            ],
        ),
    ]
